PS C:\Users\W0024618\Desktop\ai-employee-security> ^C
PS C:\Users\W0024618\Desktop\ai-employee-security> ^C
PS C:\Users\W0024618\Desktop\ai-employee-security> cd C:\Users\W0024618\Desktop\ai-employee-security
PS C:\Users\W0024618\Desktop\ai-employee-security> python -m venv venv
Unable to copy 'C:\\Program Files\\Python313\\Lib\\venv\\scripts\\nt\\venvlauncher.exe' to 'C:\\Users\\W0024618\\Desktop\\ai-employee-security\\venv\\Scripts\\python.exe'
PS C:\Users\W0024618\Desktop\ai-employee-security> venv\Scripts\activate
(venv) PS C:\Users\W0024618\Desktop\ai-employee-security> pip install --upgrade pip
Requirement already satisfied: pip in c:\users\w0024618\desktop\ai-employee-security\venv\lib\site-packages (25.1.1)
(venv) PS C:\Users\W0024618\Desktop\ai-employee-security> pip install pandas scikit-learn joblib fastapi uvicorn python‐dotenv pyodbc sqlalchemy
ERROR: Invalid requirement: 'python‐dotenv': Expected end or semicolon (after name and no valid version specifier)
    python‐dotenv
          ^
(venv) PS C:\Users\W0024618\Desktop\ai-employee-security> cd src
(venv) PS C:\Users\W0024618\Desktop\ai-employee-security\src> python extract.py
⏱️  Detected timestamp column: 'LocaleMessageTime'
C:\Users\W0024618\Desktop\ai-employee-security\src\extract.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["LocaleMessageTime"] = pd.to_datetime(
✅ Rows loaded: 310531
     LocaleMessageTime    Dateonly Swipe_Time EmployeeID        ObjectName1        PersonnelType  CardNumber AdmitCode     Direction                                               Door Rejection_Type
21 2025-05-31 17:29:00  2025-05-31   17:29:00          0   Vasulkar, Sachin  Property Management      410317     Admit   InDirection             APAC_IN_PUN_PODIUM_ST2 DOOR 2 (YELLOW)            NaN
22 2025-05-31 16:01:00  2025-05-31   16:01:00          0   Vasulkar, Sachin  Property Management      410317     Admit   InDirection     APAC_IN_PUN_PODIUM_YELLOW_RECEPTION ENTRY-DOOR            NaN
23 2025-05-31 09:39:00  2025-05-31   09:39:00          0       Maurya, Anil  Property Management      410377     Admit  OutDirection      APAC_IN_PUN_PODIUM_GREEN_RECEPTION ENTRY-DOOR            NaN
24 2025-05-31 09:30:00  2025-05-31   09:30:00          0       Maurya, Anil  Property Management      410377     Admit   InDirection              APAC_IN_PUN_PODIUM_ST3 DOOR 2 (GREEN)            NaN
25 2025-05-31 08:30:00  2025-05-31   08:30:00   W0021569  Kamble, Babasaheb           Contractor      615768     Admit   InDirection  APAC_IN_PUN_PODIUM_YELLOW_REPRO STORE-DOOR Res...            NaN
✅ Saved DataFrame with 310531 rows to C:\Users\W0024618\Desktop\ai-employee-security\data\logs.pkl
(venv) PS C:\Users\W0024618\Desktop\ai-employee-security\src> cd src
cd : Cannot find path 'C:\Users\W0024618\Desktop\ai-employee-security\src\src' because it does not exist.
At line:1 char:1
+ cd src
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\W00246...ecurity\src\src:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

(venv) PS C:\Users\W0024618\Desktop\ai-employee-security\src> python train.py
Traceback (most recent call last):
  File "C:\Users\W0024618\Desktop\ai-employee-security\src\train.py", line 188, in <module>
    build_and_save_model()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\W0024618\Desktop\ai-employee-security\src\train.py", line 124, in build_and_save_model
    df_labeled = apply_all_labelers(df)
  File "C:\Users\W0024618\Desktop\ai-employee-security\src\train.py", line 39, in apply_all_labelers
    df = label_anomaly(df)
  File "C:\Users\W0024618\Desktop\ai-employee-security\src\labelers.py", line 14, in label_anomaly
    .rolling(f"{window_minutes}min")
     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W0024618\Desktop\ai-employee-security\venv\Lib\site-packages\pandas\core\groupby\groupby.py", line 3879, in rolling
    return RollingGroupby(
        self._selected_obj,
    ...<3 lines>...
        **kwargs,
    )
  File "C:\Users\W0024618\Desktop\ai-employee-security\venv\Lib\site-packages\pandas\core\window\rolling.py", line 713, in __init__
    super().__init__(obj, *args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\W0024618\Desktop\ai-employee-security\venv\Lib\site-packages\pandas\core\window\rolling.py", line 170, in __init__
    self._validate()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\W0024618\Desktop\ai-employee-security\venv\Lib\site-packages\pandas\core\window\rolling.py", line 1914, in _validate
    raise ValueError("window must be an integer 0 or greater")
ValueError: window must be an integer 0 or greater
(venv) PS C:\Users\W0024618\Desktop\ai-employee-security\src>












